"use client";

import { Document, Page, StyleSheet, Text, View, pdf } from "@react-pdf/renderer";
import { Download } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";

type ReceiptMilestone = {
  dateTime: string;
  duration: string;
  metadata?: string;
  text: string;
  title: string;
};

type ReceiptPdfDownloadButtonProps = {
  activeWritingTime: string;
  assignmentTitle: string;
  bulkPasteWordCount: number;
  finalWordCount: number;
  milestones: ReceiptMilestone[];
  submittedAt: string;
};

export function ReceiptPdfDownloadButton({
  activeWritingTime,
  assignmentTitle,
  bulkPasteWordCount,
  finalWordCount,
  milestones,
  submittedAt,
}: ReceiptPdfDownloadButtonProps) {
  const [isExporting, setIsExporting] = useState(false);

  async function downloadReceipt() {
    setIsExporting(true);
    try {
      const blob = await pdf(
        <ReceiptPdfDocument
          activeWritingTime={activeWritingTime}
          assignmentTitle={assignmentTitle}
          bulkPasteWordCount={bulkPasteWordCount}
          finalWordCount={finalWordCount}
          milestones={milestones}
          submittedAt={submittedAt}
        />,
      ).toBlob();
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `${safeFilename(assignmentTitle)}-trace-receipt.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(link.href);
    } finally {
      setIsExporting(false);
    }
  }

  return (
    <Button variant="outline" onClick={downloadReceipt} disabled={isExporting}>
      <Download /> {isExporting ? "Preparing PDF" : "Download receipt PDF"}
    </Button>
  );
}

export function ReceiptPdfDocument({
  activeWritingTime,
  assignmentTitle,
  bulkPasteWordCount,
  finalWordCount,
  milestones,
  submittedAt,
}: ReceiptPdfDownloadButtonProps) {
  return (
    <Document title={`${assignmentTitle} - Trace receipt`} author="Trace">
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.eyebrow}>TRACE - VERIFIED WRITING RECEIPT</Text>
          <Text style={styles.title}>{assignmentTitle}</Text>
          <Text style={styles.muted}>Submitted {submittedAt}</Text>
        </View>

        <View style={styles.metrics}>
          <Metric label="Active writing time" value={activeWritingTime} />
          <Metric label="Revision milestones" value={String(milestones.length)} />
          <Metric label="Final word count" value={finalWordCount.toLocaleString()} />
          <Metric label="Large pasted additions" value={bulkPasteWordCount ? `${bulkPasteWordCount.toLocaleString()} words` : "None"} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Writing journey</Text>
          <Text style={styles.sectionIntro}>Each milestone records a visible revision in the saved draft.</Text>
          {milestones.length === 0 ? (
            <Text style={styles.empty}>No writing milestones were recorded before submission.</Text>
          ) : (
            milestones.map((milestone, index) => (
              <View key={`${milestone.dateTime}-${index}`} style={styles.milestone} wrap={false}>
                <Text style={styles.milestoneTitle}>{milestone.title}</Text>
                <Text style={styles.milestoneText}>{milestone.text}</Text>
                <Text style={styles.milestoneMeta}>{milestone.dateTime} - {milestone.duration} active writing</Text>
                {milestone.metadata && <Text style={styles.milestoneMeta}>{milestone.metadata}</Text>}
              </View>
            ))
          )}
        </View>

        <Text fixed style={styles.footer}>Generated by Trace - proof of the writing process</Text>
      </Page>
    </Document>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>;
}

const styles = StyleSheet.create({
  page: { backgroundColor: "#f7f8f7", color: "#1d2521", fontFamily: "Helvetica", fontSize: 10, padding: 42 },
  header: { borderBottomColor: "#dbe3dc", borderBottomWidth: 1, marginBottom: 24, paddingBottom: 20 },
  eyebrow: { color: "#567160", fontSize: 8, fontWeight: 700, letterSpacing: 1.2 },
  title: { fontSize: 24, fontWeight: 700, lineHeight: 1.15, marginTop: 9 },
  muted: { color: "#65716a", fontSize: 10, marginTop: 7 },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 24 },
  metric: { backgroundColor: "#ffffff", borderColor: "#dbe3dc", borderWidth: 1, borderRadius: 6, minHeight: 58, padding: 10, width: "48.8%" },
  metricValue: { fontSize: 15, fontWeight: 700 },
  metricLabel: { color: "#69756d", fontSize: 8, marginTop: 5 },
  section: { backgroundColor: "#ffffff", borderColor: "#dbe3dc", borderWidth: 1, borderRadius: 6, padding: 16 },
  sectionTitle: { fontSize: 14, fontWeight: 700 },
  sectionIntro: { color: "#607067", lineHeight: 1.5, marginTop: 5 },
  empty: { color: "#69756d", marginTop: 15 },
  milestone: { borderLeftColor: "#78a782", borderLeftWidth: 2, marginTop: 15, paddingLeft: 10 },
  milestoneTitle: { fontSize: 11, fontWeight: 700 },
  milestoneText: { color: "#405049", lineHeight: 1.45, marginTop: 4 },
  milestoneMeta: { color: "#69756d", fontSize: 8, marginTop: 5 },
  footer: { bottom: 22, color: "#69756d", fontSize: 8, left: 42, position: "absolute", right: 42, textAlign: "center" },
});

function safeFilename(value: string) {
  return value.trim().replace(/[^a-z0-9]+/gi, "-").replace(/(^-|-$)/g, "") || "trace-receipt";
}
